// Third-party Imports
import 'react-perfect-scrollbar/dist/css/styles.css';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { headers } from 'next/headers';

// Config Imports
import { i18n } from '@/configs/i18n';

// Utility Imports
import { getSystemMode } from '@/@core/utils/serverHelpers';

// Component Imports
import TranslationWrapper from '@/hocs/TranslationWrapper';

// Type Imports
import type { Metadata } from 'next';
import type { Locale } from '@/configs/i18n';
import type { ChildrenType } from '@/@core/types';
import Providers from '@/components/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async (props: ChildrenType & { params: Promise<{ lang: Locale }> }) => {
  const params = await props.params;

  const { children } = props;

  // Vars
  const headersList = await headers();
  const systemMode = await getSystemMode();
  const direction = i18n.langDirection[params.lang];

  return (
    <TranslationWrapper headersList={headersList} lang={params.lang}>
      <html id="__next" lang={params.lang} dir={direction} suppressHydrationWarning>
        <body>
          <Providers>
            <InitColorSchemeScript attribute="data" defaultMode={systemMode} />
            {children}
          </Providers>
        </body>
      </html>
    </TranslationWrapper>
  );
};

export default RootLayout;
